# config/stocks.yaml
watchlists:
  # 港股主要股票
  hk_main:
    name: "港股主板"
    description: "香港主板市场主要股票"
    stocks:
      - "HK.00700"  # 腾讯控股
      - "HK.00005"  # 汇丰控股
      - "HK.00941"  # 中国移动
      - "HK.01299"  # 友邦保险
      - "HK.00388"  # 港交所
      - "HK.02318"  # 中国平安
      - "HK.02628"  # 中国人寿
      - "HK.00883"  # 中国海洋石油
      - "HK.01088"  # 中国神华
      - "HK.03988"  # 中国银行

  # 港股科技股
  hk_tech:
    name: "港股科技板块"
    description: "香港科技类股票"
    stocks:
      - "HK.00700"  # 腾讯
      - "HK.09988"  # 阿里巴巴
      - "HK.09618"  # 京东
      - "HK.09888"  # 百度
      - "HK.03690"  # 美团
      - "HK.02020"  # 安踏体育
      - "HK.00992"  # 联想集团

  # 测试用小型股票池
  test_small:
    name: "测试股票池"
    description: "用于开发和测试的小型股票池"
    stocks:
      - "HK.00700"  # 腾讯
      - "HK.00005"  # 汇丰
      - "HK.00941"  # 中国移动

  # 港股蓝筹股
  hk_blue_chip:
    name: "港股蓝筹股"
    description: "恒生指数成分股"
    stocks:
      - "HK.00001"  # 长和
      - "HK.00002"  # 中电控股
      - "HK.00003"  # 香港中华煤气
      - "HK.00005"  # 汇丰控股
      - "HK.00011"  # 恒生银行
      - "HK.00012"  # 恒基地产
      - "HK.00016"  # 新鸿基地产
      - "HK.00017"  # 新世界发展
      - "HK.00019"  # 太古股份公司
      - "HK.00023"  # 东亚银行
      - "HK.00027"  # 银河娱乐
      - "HK.00066"  # 港铁公司
      - "HK.00083"  # 信和置业
      - "HK.00101"  # 恒隆地产
      - "HK.00135"  # 昆仑能源
      - "HK.00144"  # 招商局港口
      - "HK.00267"  # 中信股份
      - "HK.00288"  # 万洲国际
      - "HK.00386"  # 中国石油化工
      - "HK.00388"  # 香港交易所
      - "HK.00688"  # 中国海外发展
      - "HK.00700"  # 腾讯控股
      - "HK.00762"  # 中国联通
      - "HK.00823"  # 领展房产基金
      - "HK.00836"  # 华润电力
      - "HK.00857"  # 中国石油股份
      - "HK.00883"  # 中国海洋石油
      - "HK.00939"  # 建设银行
      - "HK.00941"  # 中国移动
      - "HK.00992"  # 联想集团
      - "HK.01044"  # 恒安国际
      - "HK.01088"  # 中国神华
      - "HK.01109"  # 华润置地
      - "HK.01299"  # 友邦保险
      - "HK.01398"  # 工商银行
      - "HK.01810"  # 小米集团
      - "HK.01928"  # 金沙中国
      - "HK.02007"  # 碧桂园
      - "HK.02020"  # 安踏体育
      - "HK.02318"  # 中国平安
      - "HK.02319"  # 蒙牛乳业
      - "HK.02382"  # 舜宇光学科技
      - "HK.02628"  # 中国人寿
      - "HK.03333"  # 中国恒大
      - "HK.03988"  # 中国银行